name: ${COMPOSE_PROJECT_NAME}

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: ${MYSQL_DB_NAME}
      MYSQL_USER: ${MYSQL_DATABASE_USERNAME}
      MYSQL_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "${MYSQL_HOST_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db-dump/${DB_DUMP_FILE}:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_HOST_PORT}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./gamevalut-server
    restart: on-failure
    ports:
      - "${BACKEND_HOST_PORT}:8080"
    environment:
      MYSQL_DATABASE_DB_NAME: jdbc:mysql://mysql:3306/${MYSQL_DB_NAME}
      MYSQL_DATABASE_USERNAME: ${MYSQL_DATABASE_USERNAME}
      MYSQL_DATABASE_PASSWORD: ${MYSQL_DATABASE_PASSWORD}
      REDIS_HOST_URL: redis
      REDIS_PORT: 6379
      MY_AWS_ACCESS_KEY: ${MY_AWS_ACCESS_KEY}
      MY_AWS_SECRET_KEY: ${MY_AWS_SECRET_KEY}
      AWS_USER_PROFILE_IMAGE_BUCKET_NAME: ${AWS_USER_PROFILE_IMAGE_BUCKET_NAME}
      AWS_GAME_FILES_BUCKET_NAME: ${AWS_GAME_FILES_BUCKET_NAME}
      AWS_GAME_IMAGES_BUCKET_NAME: ${AWS_GAME_IMAGES_BUCKET_NAME}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  admin-client:
    image: petaaar/gamevault-admin-client:latest
    ports:
      - "${ADMIN_CLIENT_HOST_PORT}:80"
    environment:
      VITE_API_URL: ${VITE_API_URL}
    depends_on:
      - backend

volumes:
  mysql_data:
  redis_data:
